# https://taskfile.dev

version: '3'

tasks:
  clean_debug:
    cmds:
      - rm -rf build/Debug

  clean_release:
    cmds:
      - rm -rf build/Release

  config_debug:
    cmds:
      - cmake --preset=debug

  config_release:
    cmds:
      - cmake --preset=release

  build_debug:
    cmds:
      - task: config_debug
      - cmake --build --preset=debug

  build_release:
    cmds:
      - task: config_release
      - cmake --build --preset=default

  run_debug:
    cmds:
      - task: build_debug

  run_release:
    cmds:
      - task: build_release

  test:
    cmds:
      - task: build_debug
      - ctest --preset=debug
